version: '3.8'

services:
  ev-charging-tracker:
    build: .
    container_name: ev-charging-tracker
    ports:
      - "3001:3001"
    volumes:
      # Persist SQLite database
      - ev_data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "fetch('http://localhost:3001/api/health').then(r=>r.ok?process.exit(0):process.exit(1)).catch(()=>process.exit(1))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ev-tracker.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.ev-tracker.entrypoints=websecure"
      - "traefik.http.routers.ev-tracker.tls.certresolver=letsencrypt"
      - "traefik.http.services.ev-tracker.loadbalancer.server.port=3001"

volumes:
  ev_data:
    driver: local